# Generated by Django 3.1.1 on 2020-10-04 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 22, 53, 58, 921674)),
        ),
        migrations.AddField(
            model_name='commentary',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 22, 53, 58, 922121)),
        ),
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 22, 53, 58, 921320)),
        ),
    ]
