# Generated by Django 3.1.1 on 2020-10-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201016_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(default='Default Title'),
            preserve_default=False,
        ),
    ]
