# Generated by Django 3.1.1 on 2020-10-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Comment',
        ),
    ]
